input:
  file:
    paths: ["${BENTO_FILE_PATH}"]
    scanner:
      decompress:
        algorithm: "gzip"
        into:
          lines: {}

pipeline:
  processors:
    - mapping: |
        # Get cluster routing target pipeline by AWS account id
        # This file_rel call is cached so it only reads the file once, not every record
        let routing = file_rel("aws-routing.json").parse_json()
        if this.recipientAccountId != "" {
          let lookupPipeline = $routing.get(this.recipientAccountId).target_pipeline
          if $lookupPipeline != null {
            root = this
            root.lookup_target_pipeline = $lookupPipeline
          } else {
            root = this
            root.lookup_target_pipeline = "default_gis"
          }
        } else {
          root = this
          root.lookup_target_pipeline = "default_gis"
        }

output:
  file:
    path: "${BENTO_OUTPUT_PATH}"
    codec: lines